name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for web gl
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false
          path: /home/runner/work/UnityUI/UnityUI/src/unity\ ui/
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL 
          projectPath: /home/runner/work/UnityUI/UnityUI/src/unity\ ui/
      - uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: build/WebGL
